#!/usr/bin/python
# for bash we need to add the following to our .bashrc
# export PYTHONPATH=$PYTHONPATH:$RMANTREE/bin
import getpass
import time
# import the python renderman library
import prman

def Cube(width,height,depth) :
  w=width/2.0
  h=height/2.0
  d=depth/2.0
  ri.ArchiveRecord(ri.COMMENT, 'Cube Generated by Cube Function')
  #rear
  face=[-w, -h, d, -w, h, d, w, -h, d, w, h, d]
  ri.Patch("bilinear",{'P':face})
  #front
  face=[-w, -h, -d, -w, h, -d, w, -h, -d, w, h, -d]
  ri.Patch("bilinear",{'P':face})
  #left
  face=[-w, -h, -d, -w, h, -d, -w, -h, d, -w, h, d]
  ri.Patch("bilinear",{'P':face})
  #right
  face=[w, -h, -d, w, h, -d, w, -h, d, w, h, d]
  ri.Patch("bilinear",{'P':face})
  #bottom
  face=[w, -h, d, w, -h, -d, -w, -h, d, -w, -h, -d]
  ri.Patch("bilinear",{'P':face})
  #top
  face=[w, h, d, w, h, -d, -w, h, d, -w, h, -d]
  ri.Patch("bilinear",{'P':face})
  ri.ArchiveRecord(ri.COMMENT, '--End of Cube Function--')

ri = prman.Ri() # create an instance of the RenderMan interface

filename = "__render" #"HelloWorld.rib"
# this is the begining of the rib archive generation we can only
# make RI calls after this function else we get a core dump
ri.Begin('simplescene.rib')
# ArchiveRecord is used to add elements to the rib stream in this case comments
# note the function is overloaded so we can concatinate output
ri.ArchiveRecord(ri.COMMENT, 'Comments start with a #')
ri.ArchiveRecord(ri.COMMENT, 'File simplescene.rib #')
ri.ArchiveRecord(ri.COMMENT, "Created by " + getpass.getuser())
ri.ArchiveRecord(ri.COMMENT, "Creation Date: " +time.ctime(time.time()))

# now we add the display element using the usual elements
# FILENAME DISPLAY Type Output format
ri.Display("Simplescene.exr", "file", "rgba")
# Specify PAL resolution 1:1 pixel Aspect ratio
ri.Format(720,576,1)
# now set the projection to perspective
ri.Projection(ri.PERSPECTIVE)

# now we start our world
ri.WorldBegin()
groud_position = -1
# move back 2 in the z so we can see what we are rendering
ri.ArchiveRecord(ri.COMMENT, 'move our world back 2 in the z so we can see it')
ri.Translate(0,0,2)
ri.ArchiveRecord(ri.COMMENT, 'draw ground with bilinear patch')
ri.TransformBegin()
height = 0.1
ri.Translate(0, groud_position - height/2, 0)
ri.AttributeBegin()
ri.Color([0.11, 0.49, 0.89])
Cube(7, height, 4)
ri.AttributeEnd()
ri.TransformEnd()

ri.ArchiveRecord(ri.COMMENT, 'draw a sphere primitive')
ri.TransformBegin()
radius = 0.5
ri.Translate(0, groud_position + radius, 0)
ri.AttributeBegin()
ri.Color([1, 0, 0])
ri.Sphere (radius, -radius, radius, 360)
ri.AttributeEnd()
ri.TransformEnd()

# end our world
ri.ArchiveRecord(ri.COMMENT, 'end our world')
ri.WorldEnd()
# and finally end the rib file
ri.End()
